---
output: pdf_document
header-includes: \usepackage{placeins}
---

# Discussion of Author P. Scrivener 

Based on our assumed results, we found a strong correlation in cognitive performance when white noise is presented to the participant. This suggests first off that cognitive performance and memory retrieval are affected by neuronal firing of dopamine pathways. That there is variance in baseline neuronal firing and that raising this baseline will positively affect cognitive performance up to a point. This has a theoretic basis in Stochastic Resonance and how stochastic noise can increase the signal-to-noise ratio in all sorts of both natural and man-made systems. Our findings suggest that stochastic resonance is indeed found in the brain both at the neuron level and at the pathway level. Our findings also confirm that noise can be found in the auditory system. Perhaps the most interesting result of our findings is that noise presented to the auditory system can influence neuronal firing at a broad level which in turn influences cognitive performance. Just like noise can have a positive effect on signal detection, it can also have a positive affect on a more complex process like memory retrieval. 

These findings also suggest that auditory stimuli can affect more than just the perceptual system of the noise itself, it can influence a broader range of attention and cognitive systems. This could be interpreted as audio stimuli could influence arousal in a more general way, making the subject more alert and attentive. It is important to make the distinction however, that these effects are only from white noise stimuli, not more variant audio stimuli. Music is a good example of auditory stimuli that influences arousal, yet can interfere with attention and memory retrieval processes in a negative way. It is apperent that auditory stimuli influences neuronal firing thus when auditory stimulus that is presented as white noise, the effects on the brain create a more pronounced stochastic resonance. This can have many benefits than just the ones presented in this experiment, including increased performance in memory retrieval, increased performance in learning tasks, and the well studied increase in signal detection. 

There was also an increase performance on the simple game task when a constant rhythmic tone was presented to the participant. This increase in performance was not apparent in the memory retrieval task. This suggests that the constant rhythmic tone did not have a direct effect on cognitive performance, but did have an affect in some other way. We suggest the reason for this increase in performance to be due to a phenomenom labeled auditory cueing. The cueing effect has been found in many perceptual systems, not just the auditory system. However, the effect that we believe we are seeing with these results is rhythmic auditory cueing having a positive performance on motor function. Specifically the constant tone helps the participant tap the keyboard at a constant interval to keep the bird in the air. The effects of auditory cueing have been studied extensively in initiating motor action and we believe these effects are no different. Just like we find it almost natural to drum our finger or tap our foot along to the beat of a song, the rhythmic motion of the game task in this experiment is no different. These effects become obvious when you look at the detrimental effects that a random audio tone had on performance in the game task. When the tone was not constant, the auditory cueing effect largely dissapeared or almost had the opposite effect. The participant found it harder to keep their motor initiation constant when an irregular tone was present.

Overall, the effect of stochastic resonance, although extensive in some aspects of natural phenomena, need to be researched more thoroughly in psychological research beyond mere signal detection. If certain aspects of research on auditory stimulus effects on more general neuronal firing, including the effects on the firings whithin the dopaminergic pathway are correct. Then there could be major possibilities for non-medication based treatment on attention deficit and other cognitive deficits. The prevelance and implications of stochastic resonance on neuronal firings, although vast, have room for elaboration. The effect of other presentations of noise based stimuli on cognitive performance should also be explored, not just on auditory noise. The implications of stochastic resonance are very important for signal detection, yet I believe the implications of this phenomena go far past signal-detection, and can be more generally applied in the future.
