---
output: pdf_document
header-includes: \usepackage{placeins}
---

\newpage

# Introduction

It is widely believed that auditory noise has a detrimental effect on both cognition and attention. In this experiment we attempt to explore the possible positive effects that noise can have on cognitive tasks. One auditory phenomenon that we explore is Stochastic Resonance (SR), the idea that an optimal level of noise added to a system can enhance the performance of a non-linear system. The idea of stochastic resonance has been observed across disciplines and we aim to explore the effects that it may have on cognition. Input Stochastic Resonance in a auditory scenario is called white noise. This is defined as auditory tones being presented with equal intensity at different frequencies.

Evidence of Stochastic Resonance has been found in the nervous system. This effect can be seen as baseline neuronal firing within the brain with no input or outside stimuli. This effect has been viewed in all sorts of perception systems, ranging from audition to visual [@MOSS2004267]. The basic idea of stochastic resonance is that added noise to a system can enhance a signal strength. This can be scaled up to entire pathways present in the brain like the dopaminergic pathway. Recent evidence suggests that the dopaminergic pathway influences attention and cognition [@BELL2020]. There is a baseline firing rate dopamine neurons in the brain and the same basic principles of stochastic resonance apply. By adding input noise to the system we believe that we can enhance signal strength, the signal in this case would be memory retrieval. Stochastic resonance has been found specifically in the auditory region. The auditory system overall is nonlinear [@PHYS5232]. It has been shown that increased noise can increase signal detection of tones [@ZENG2000]. It has been found that stochastic noise stimulation via transcranial electric stimulation (tES) both have positive effect on learning [@Fertonani15416] and general cognitive performance [@MULQUINEY20112384]. We believe that stochastic auditory noise can have the same effect on neuronal firing and thus the same effect on cognitive performance.

An experiment that we draw evidence from is The effects of background white noise on memory performance in inattentive school children, [@SODERLAND2010]. This experiment found that inattentive children had an increase of memory performance when listening to white noise. The proposed explanation for this effect was that a hypodopaminergic brain does not have the same baseline dopamine neuronal firing. This neuronal firing can then be increased by input noise and thus increase cognitive performance. We believe that this effect can be replicated with any participant group, even if they have no sign of attention deficit. If the optimal decibel level is reached, there will be increased performance across the board because of an increase in neuronal firing. Another experiment found that white noise increased reaction time on an arithmetical recall task [@USHER2000]. 

We also aim to explore other possible improvements auditory stimulus could have on performance. There is vast research done on the effect of rhythmic auditory cueing for movement rehabilitation [@REBECCA2014]. We seem to have an innate sense to dance to rhythm of music. We would like to explore this as another possible avenue for improved performance in a simple computer game scenario. 
